services:
  nginx:
    build: 
      context: ./environment
      dockerfile: Dockerfile
    ports:
      - "${HTTP_PORT}:80"
    environment:
    - NGINX_PORT=80
    volumes:
        - ./:/workspace
        - ./:/var/www/api

    working_dir: /workspace
    stdin_open: true
    tty: true
    restart: no
